using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using System.Management;

namespace VMFPassThrough
{
#if !PUBLIC
	class Security
	{
		static string[] ids = new string[] {
			// Here goes old hardware IDs generated by Security.GetMachineID()
		};
		static List<string> allowedMachineIDs = new List<string>(ids);

		public static string GetMachineID()
		{
			// Getting CPU ID
			string cpuInfo = string.Empty;
			ManagementClass mc = new ManagementClass("win32_processor");
			ManagementObjectCollection moc = mc.GetInstances();

			foreach (ManagementObject mo in moc)
			{
				if (cpuInfo == "")
				{
					//Get only the first CPU's ID
					cpuInfo = mo.Properties["processorID"].Value.ToString();
					break;
				}
			}

			// Getting disk drive ID
			ManagementObject dsk = new ManagementObject(@"win32_logicaldisk.deviceid=""C:""");
			dsk.Get();
			string volumeSerial = dsk["VolumeSerialNumber"].ToString();

			return cpuInfo + volumeSerial;
		}

		public static bool IsMachineAllowed()
		{
			if (allowedMachineIDs.IndexOf(GetMachineID()) >= 0)
				return true;

			return false;
		}
	}
#endif
}
